export enum CategoryConstants {
    LOAD_IN_PROGRESS = 'LOAD_CATEGORIES_IN_PROGRESS',
    LOAD_SUCCESS = 'LOAD_CATEGORIES_SUCCESS',
    LOAD_FAILED = 'LOAD_CATEGORIES_FAILED',
    DELETE_BY_ID = 'DELETE_CATEGORY_BY_ID',
    UPDATE_BY_ID = 'UPDATE_CATEGORY_BY_ID',
};