export enum GradeConstants {
    LOAD_IN_PROGRESS = 'LOAD_GRADES_IN_PROGRESS',
    LOAD_SUCCESS = 'LOAD_GRADES_SUCCESS',
    LOAD_FAILED = 'LOAD_GRADES_FAILED',
    DELETE_BY_ID = 'DELETE_GRADE_BY_ID',
    UPDATE_BY_ID = 'UPDATE_GRADE_BY_ID',
};