export enum GroupConstants {
    LOAD_IN_PROGRESS = 'LOAD_GROUPS_IN_PROGRESS',
    LOAD_SUCCESS = 'LOAD_GROUPS_SUCCESS',
    LOAD_FAILED = 'LOAD_GROUPS_FAILED',
    DELETE_BY_ID = 'DELETE_GROUP_BY_ID',
    UPDATE_BY_ID = 'UPDATE_GROUP_BY_ID',
    SAVE_IN_PROGRESS = 'SAVE_GROUPS_IN_PROGRESS',
    SAVE_FAILED = 'SAVE_GROUPS_FAILED',
    SAVE_SUCCESS = 'SAVE_GROUPS_SUCCESS'
};