export enum MatchConstants {
    LOAD_IN_PROGRESS = 'LOAD_MATCHES_IN_PROGRESS',
    LOAD_SUCCESS = 'LOAD_MATCHES_SUCCESS',
    LOAD_FAILED = 'LOAD_MATCHES_FAILED',
    DELETE_BY_ID = 'DELETE_MATCH_BY_ID',
    UPDATE_BY_ID = 'UPDATE_MATCH_BY_ID',
    UPDATE_IN_PROGRESS = 'MATCH_UPDATE_IN_PROGRESS',
};