export enum RegistrationConstants {
    LOAD_SUCCESS = 'ALL_REGISTRATION_PREREQS_LOADED',
    USER_UPDATE = 'UPDATE_REGISTRATION_BY_USER',
    SERVER_UPDATE = 'UPDATE_REGISTRATION_FROM_SERVER',
    SAVE_IN_PROGRESS = 'SAVE_REGISTRATION_IN_PROGRESS',
    SAVE_SUCCESS = 'SAVE_REGISTRATION_SUCCESS',
    SAVE_FAILED = 'SAVE_REGISTRATION_FAILED',
};