export enum TeamConstants {
    LOAD_IN_PROGRESS = 'LOAD_TEAMS_IN_PROGRESS',
    LOAD_SUCCESS = 'LOAD_TEAMS_SUCCESS',
    LOAD_FAILED = 'LOAD_TEAMS_FAILED',
    DELETE_BY_ID = 'DELETE_TEAM_BY_ID',
    UPDATE_BY_ID = 'UPDATE_TEAM_BY_ID',
    SAVE_IN_PROGRESS = 'SAVE_TEAM_IN_PROGRESS',
    SAVE_FAILED = 'SAVE_TEAM_FAILED',
    SAVE_SUCCESS = 'SAVE_TEAM_SUCCESS'
};